





# services:
#   keycloak_server:
#     image: quay.io/keycloak/keycloak:23.0.3
#     command: start-dev # add a space before this line
#     environment:
#       KC_DB: postgress
#       KC_DB_URL_HOST: postgres_keycloack_server
#       KC_DB_URL_DATABASE: keycloakc_Db
#       KC_DB_PASSWORD: password123
#       KC_DB_USERNAME: keycloak_user
#       KC_DB_SCHEMA: public
#       KEYCLOAK_ADMIN: admin
#       KEYCLOAK_ADMIN_PASSWORD: admin
#     ports:
#       - "8890:8080"
#     depends_on:
#       postgres_keycloak_demo:
#         condition: service_healthy
#     networks: 
#       - keycloak_dev_network

#   postgres_keycloak_demo:
#     image: postgres:14.2
#     command: postgres -c "max_connections=200"
#     volumes: 
#       - pgdata.keycloak_db_storage: /var/lib/postgresql/data
#     environment:
#       POSTGRES_DB: keycloakc_Db
#       POSTGRES_USER: keycloak_user
#       POSTGRES_PASSWORD: password123
#     healthcheck:
#       test: "exit 0"
#     ports:
#       - "5436:5432"
#     networks: 
#       - keycloak_dev_network
#   volumes:
#     pgdata.keycloak_db_storage:
#   networks:
#     keycloak_dev_network:
#       driver: bridge
